Fix patch route (#23)
### What this PR does

* Fix patch route for it to always return the update org

### Context

Originally, I though there was an error with the `gracePeriod` not being updated correctly (which is silly, because we have tests for that!). I tested the DB and it worked correctly:

```
2016-08-24 16:45:07 hiphipjorge at Jorges-MacBook-Pro in ~/runnable/big-poppa on master [$]
$ psql -U big_poppa -d big_poppa
psql (9.5.3)
Type "help" for help.

big_poppa=# select id,trial_end,active_period_end,grace_period_end,updated_at from organizations;
 id |       trial_end        |     active_period_end      |    grace_period_end    |         updated_at
----+------------------------+----------------------------+------------------------+----------------------------
 78 | 2016-08-27 16:52:52-07 | 2016-08-13 16:52:51.848-07 | 2016-08-30 16:52:52-07 | 2016-08-13 18:13:01.153-07
 79 | 2016-08-30 16:55:55-07 | 2016-08-16 16:48:12.131-07 | 2016-09-02 16:55:55-07 | 2016-08-16 16:55:55.496-07
(2 rows)

big_poppa=#
big_poppa=# UPDATE organizations SET active_period_end = TIMESTAMP 2016-09-24T16:46:24.576Z  WHERE id = 78;
ERROR:  syntax error at or near "2016"
LINE 1: ...E organizations SET active_period_end = TIMESTAMP 2016-09-24...
                                                             ^
big_poppa=# UPDATE organizations SET active_period_end = TIMESTAMP '2016-09-24T16:46:24.576Z'  WHERE id = 78;
UPDATE 1
big_poppa=# select id,trial_end,active_period_end,grace_period_end,updated_at from organizations;
 id |       trial_end        |     active_period_end      |      grace_period_end      |         updated_at
----+------------------------+----------------------------+----------------------------+----------------------------
 79 | 2016-08-30 16:55:55-07 | 2016-08-16 16:48:12.131-07 | 2016-09-02 16:55:55-07     | 2016-08-16 16:55:55.496-07
 78 | 2016-08-27 16:52:52-07 | 2016-09-24 16:46:24.576-07 | 2016-09-27 16:46:24.576-07 | 2016-08-13 18:13:01.153-07
(2 rows)
```

So then I just tested the route and found this:

```
root@ip-10-4-13-234:/home/ubuntu# curl --request PATCH -H "Content-Type: application/json" --data '{ "activePeriodEnd": "2016-09-16T16:46:24.576Z" }' 0.0.0.0:7788/organization/73/ | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   561  100   512  100    49  24001   2297 --:--:-- --:--:-- --:--:-- 24380
{
    "activePeriodEnd": "2016-09-16T16:46:24.576Z",
    "allowed": true,
    "createdAt": "2016-08-23T20:48:22.928Z",
    "firstDockCreated": true,
    "githubId": 21206356,
    "gracePeriodEnd": "2016-09-27T16:46:24.576Z",
    "hasPaymentMethod": false,
    "id": 73,
    "isActive": true,
    "isInActivePeriod": true,
    "isInGracePeriod": false,
    "isInTrial": true,
    "lowerName": "bigpopppatest2",
    "name": "BigPopppaTest2",
    "stripeCustomerId": "cus_93tcb2A5IAaOr5",
    "trialEnd": "2016-09-06T20:48:23.000Z",
    "updatedAt": "2016-08-23T23:37:18.744Z",
    "updated_at": "2016-08-24T16:53:50.217Z"
}
root@ip-10-4-13-234:/home/ubuntu# curl 0.0.0.0:7788/organization/73/ | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   653  100   653    0     0  67830      0 --:--:-- --:--:-- --:--:-- 72555
{
    "activePeriodEnd": "2016-09-16T16:46:24.576Z",
    "allowed": true,
    "createdAt": "2016-08-23T20:48:22.928Z",
    "firstDockCreated": true,
    "githubId": 21206356,
    "gracePeriodEnd": "2016-09-19T16:46:24.576Z",
    "hasPaymentMethod": false,
    "id": 73,
    "isActive": true,
    "isInActivePeriod": true,
    "isInGracePeriod": false,
    "isInTrial": true,
    "lowerName": "bigpopppatest2",
    "name": "BigPopppaTest2",
    "stripeCustomerId": "cus_93tcb2A5IAaOr5",
    "trialEnd": "2016-09-06T20:48:23.000Z",
    "updatedAt": "2016-08-24T16:53:50.217Z",
    "users": [
        {
            "_pivot_organization_id": 73,
            "_pivot_user_id": 51,
            "createdAt": "2016-08-03T20:38:21.791Z",
            "githubId": 1981198,
            "id": 51,
            "isActive": true,
            "updatedAt": "2016-08-18T01:14:15.119Z"
        }
    ]
}
```

### Reviewers

- [x] @anandkumarpatel 

### Tests 

- [x] Update `trialEnd` through `PATCH` route
- [x] Update `activePeriodEnd` through `PATCH` route